# Build Stage
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

# Copy the necessary files for restoring
COPY *.csproj ./
RUN dotnet restore

# Copy the source code and publish the application
COPY . ./
RUN dotnet publish -c Release -o out

# Runtime Stage
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

# Copy the published output from the build stage
COPY --from=build /app/out .  

# Set the entry point for the container
ENTRYPOINT ["dotnet", "SampleCICD.dll"]